version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Memory_usage
    hostname: Memory_usage
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./storage/ram_usage_data:/app/storage
    depends_on:
      - redis

  redis:
    image: redis
    container_name: celery_redis
    env_file:
      - .env
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

  flower:
    image: mher/flower
    container_name: comment-flower
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH:-myuser:mypassword}
    command: celery flower

volumes:
  redis-data:
  ram_usage_data: